defaultBaseImage: gcr.io/distroless/static
builds:
  - id: db1000n
    dir: .
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=encrypted
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X github.com/Arriven/db1000n/src/utils/ota.Version={{ .Env.VERSION }}
      - -X github.com/Arriven/db1000n/src/utils.ProtectedKeys={{ .Env.PROTECTED_KEYS }}
      - -X github.com/Arriven/db1000n/src/job/config.DefaultConfig={{ .Env.DEFAULT_CONFIG_VALUE }}
      - -X github.com/Arriven/db1000n/src/job.DefaultConfigPathCSV={{ .Env.DEFAULT_CONFIG_PATH }}
