jobs:
  - type: sequence
    args:
      jobs:
        - type: http
          args:
            count: 1
            method: GET
            path: "https://localhost:8080/search?searchid={{ random_uuid }}&l10n=ru&reqenc=&text={{ random_uuid }}"
            client:
              timeout: 1s
        - type: http
          args:
            method: GET
            path: "https://localhost:8090/search?searchid={{ random_uuid }}&l10n=ru&reqenc=&text={{ random_uuid }}"
            client:
              proxy_urls: '{{ join get_proxylist "," }}'
