replicaCount: 1

image:
  repository: ghcr.io/arriven/db1000n
  pullPolicy: IfNotPresent
  # Available images: https://github.com/Arriven/db1000n/pkgs/container/db1000n
  tag: latest

resources: {}
  # limits:
  #   cpu: 1
  #   memory: 1Gi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
