#cloud-config
runcmd:
  # replace with the latest version
  - wget -c https://github.com/Arriven/db1000n/releases/download/v0.8.15/db1000n-v0.8.15-linux-amd64.tar.gz -O - | tar -xz
  - systemctl daemon-reload
  - systemctl enable db1000n
  - systemctl start db1000n

write_files:
- content: |
    [Unit]
    Description=db1000n service
    After=syslog.target network.target

    [Service]
    SuccessExitStatus=143

    User=root
    Group=root

    Type=simple

    WorkingDirectory=/
    ExecStart=/db1000n
    ExecStop=/bin/kill -15 $MAINPID

    [Install]
    WantedBy=multi-user.target
  path: /etc/systemd/system/db1000n.service
