name: docker-lint

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: Dockerfile
