# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build with ko

on:
  push:
    branches: ["main"]
    tags: ["**"]

env:
  DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/db1000n-beta

jobs:
  push_to_registry:
    name: Publish docker image with ko
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.6
      - run: KO_DOCKER_REPO=${DOCKER_REPO,,} ko publish --bare --tags ${{ github.ref_name }},latest --platform all .
        env:
          VERSION: ${{ github.ref_name }}-beta
          PROTECTED_KEYS: ${{ secrets.PROTECTED_KEYS }}
          DEFAULT_CONFIG_VALUE: ${{ secrets.DEFAULT_CONFIG }}
          DEFAULT_CONFIG_PATH: ${{ secrets.DEFAULT_CONFIG_PATH }}
