on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go webassembly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: js
          goarch: wasm
