name: terraform-md

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
    paths:
      - "terraform/**"
jobs:
  markdownlint:
    name: Lint repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Install mdl
        run: gem install mdl
      - name: Run markdownlint
        run: mdl -s ./db1000n.rb .
