on:
  push:
    branches:
      - "main"
  pull_request:

name: Test install.sh
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Installer
        run: ./install.sh
