name: Test install.sh

on:
  push:
    branches:
      - "main"
    paths:
      - 'install.sh'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
      - name: Installer
        run: ./install.sh
