name: Test install.sh

on:
  push:
    branches:
      - "main"
    paths:
      - 'install.sh'

jobs:
  installer-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run ShellCheck
        run: docker run --rm -v "$PWD:/mnt" koalaman/shellcheck:stable instsall.sh
      - name: Installer
        run: ./install.sh
